apiVersion: apps/v1
kind: Deployment
metadata:
  name: datetime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datetime
  template:
    metadata:
      labels:
        app: datetime
    spec:
      containers:
        - name: datetime
          image: pranovsakthi/datetime:1.0
          ports:
            - containerPort: 8080
